add_newline = false

format = \"\"\"
$directory$git_branch$git_status$python$cmd_duration
$character
\"\"\"

[directory]
style = \"bold blue\"
truncation_length = 3

[git_branch]
symbol = \"î‚  \"
style = \"bold cyan\"

[git_status]
style = \"bold yellow\"
format = '([$all_status]($style) )'

[python]
style = \"bold purple\"
format = '[ğŸ $version]($style) '

[cmd_duration]
min_time = 500
style = \"bold magenta\"
format = \"[â± $duration]($style) \"

[character]
success_symbol = \"[âœ](bold cyan)\"
error_symbol = \"[âœ—](bold red)\"
